from __future__ import annotations  # noqa: D100

COLLECTOR_SCANNER_CLASS_PATHS: dict[str, str] = {
    "account-cost-risk-signal-review": ("unio_collector.scanners.account_risk.cost.collector:AccountCostRiskSignalCollector"),
    "active-security-finding-review": ("unio_collector.scanners.security_finding.active.collector:ActiveSecurityFindingReviewCollector"),
    "api-gateway-cost-review": ("unio_collector.scanners.platform.api_gateway.collector:ApiGatewayCostReviewCollector"),
    "athena-query-efficiency-review": ("unio_collector.scanners.analytics_ai.athena.collector:AthenaQueryEfficiencyReviewCollector"),
    "aws-config-compliance-review": ("unio_collector.scanners.config.compliance.collector:AwsConfigComplianceReviewCollector"),
    "aws-security-service-coverage-review": (
        "unio_collector.scanners.security_governance.service.coverage.collector:AwsSecurityServiceCoverageReviewCollector"
    ),
    "backup-retention-review": ("unio_collector.scanners.collection.backup:BackupRetentionReviewCollector"),
    "bedrock-cost-review": ("unio_collector.scanners.analytics_ai.bedrock.collector:BedrockCostReviewCollector"),
    "billing-alerts-and-budgets-review": ("unio_collector.scanners.billing.collector:BillingAlertsAndBudgetsCollector"),
    "cloudfront-alb-origin-protection-review": (
        "unio_collector.scanners.network.cloudfront_alb_protection.collector:CloudFrontAlbOriginProtectionReviewCollector"
    ),
    "cloudfront-origin-cost-review": ("unio_collector.scanners.network.cloudfront_origin.collector:CloudFrontOriginCostReviewCollector"),
    "cloudtrail-cost-governance-review": ("unio_collector.scanners.audit_cost.cloudtrail.cost.collector:CloudTrailCostGovernanceReviewCollector"),
    "cloudtrail-security-posture-review": ("unio_collector.scanners.audit_cost.cloudtrail.security.collector:CloudTrailSecurityPostureReviewCollector"),
    "cloudwatch-idle-log-review": ("unio_collector.scanners.cloudwatch.log_activity.idle:CloudWatchIdleLogReviewCollector"),
    "cloudwatch-log-cost-and-relevance-review": ("unio_collector.scanners.cloudwatch.log_cost.collector:CloudWatchLogCostRelevanceCollector"),
    "cloudwatch-log-groups-without-retention": ("unio_collector.scanners.cloudwatch.log_retention.collector:CloudWatchLogRetentionCollector"),
    "commitment-and-pricing-review": ("unio_collector.scanners.cost_explorer.commitment.collection:CommitmentAndPricingReviewCollector"),
    "compute-optimizer-recommendation-review": ("unio_collector.scanners.aws_native.compute_optimizer.collector:ComputeOptimizerRecommendationReviewCollector"),
    "config-cost-governance-review": ("unio_collector.scanners.config.cost_governance.collector:ConfigCostGovernanceReviewCollector"),
    "cost-explorer-service-delta": ("unio_collector.scanners.cost_explorer.service_delta.collector:CostExplorerServiceDeltaCollector"),
    "cost-optimization-hub-recommendation-review": ("unio_collector.scanners.aws_native.cost_hub.collector:CostOptimizationHubRecommendationReviewCollector"),
    "cost-spike-analysis": ("unio_collector.scanners.cost_explorer.spike.collector:CostSpikeAnalysisCollector"),
    "cur-data-export-attribution": ("unio_collector.scanners.cur_data_export.collector:CurDataExportAttributionCollector"),
    "data-transfer-cost-review": ("unio_collector.scanners.data_transfer.collector:DataTransferCostReviewCollector"),
    "dynamodb-cost-governance-review": ("unio_collector.scanners.dynamodb.cost_governance.collector:DynamoDbCostGovernanceReviewCollector"),
    "ec2-idle-instance-review": ("unio_collector.scanners.ec2.idle_instance.collector:Ec2IdleInstanceReviewCollector"),
    "ec2-security-group-exposure-review": ("unio_collector.scanners.ec2.security_group.collector:Ec2SecurityGroupExposureReviewCollector"),
    "ec2-stopped-instances-with-storage": ("unio_collector.scanners.ec2.instance_storage.collector:StoppedInstanceStorageCollector"),
    "ec2-unassociated-elastic-ips": ("unio_collector.scanners.ec2.elastic_ip.collector:UnassociatedElasticIpCollector"),
    "ec2-unattached-ebs-volumes": ("unio_collector.scanners.ec2.ebs.collection.unattached:UnattachedEbsVolumeCollector"),
    "ecr-image-scan-posture-review": ("unio_collector.scanners.ecr.image_scan.collector:EcrImageScanPostureReviewCollector"),
    "ecs-cost-governance-review": ("unio_collector.scanners.platform.ecs.collector:EcsCostGovernanceReviewCollector"),
    "eks-cost-risk-review": ("unio_collector.scanners.platform.eks.collector:EksCostRiskReviewCollector"),
    "elasticache-cost-review": ("unio_collector.scanners.platform.elasticache.collector:ElastiCacheCostReviewCollector"),
    "encryption-baseline-review": ("unio_collector.scanners.security_governance.encryption.collector:EncryptionBaselineReviewCollector"),
    "extended-support-and-eol-review": ("unio_collector.scanners.lifecycle.collector:ExtendedSupportAndEolReviewCollector"),
    "free-tier-usage-review": ("unio_collector.scanners.free_tier.collector:FreeTierUsageReviewCollector"),
    "glue-job-crawler-cost-review": ("unio_collector.scanners.analytics_ai.glue.collector:GlueJobCrawlerCostReviewCollector"),
    "guardduty-cost-governance-review": ("unio_collector.scanners.security_governance.guardduty.collector:GuardDutyCostGovernanceReviewCollector"),
    "iam-access-analyzer-evidence-review": ("unio_collector.scanners.iam.access_analyzer.collector:IamAccessAnalyzerEvidenceReviewCollector"),
    "iam-account-security-review": ("unio_collector.scanners.iam.account_security.collector:IamAccountSecurityCollector"),
    "iam-identity-center-visibility-review": ("unio_collector.scanners.iam.identity_center.collector:IamIdentityCenterVisibilityReviewCollector"),
    "idle-zombie-resource-detector": ("unio_collector.scanners.idle.collector:IdleZombieResourceCollector"),
    "kms-cost-governance-review": ("unio_collector.scanners.kms.cost_governance.collector:KmsCostGovernanceReviewCollector"),
    "kms-key-posture-review": ("unio_collector.scanners.kms.key_posture.collector:KmsKeyPostureReviewCollector"),
    "lambda-cost-cycle-risk-review": ("unio_collector.scanners.collection.lambda_cycle:LambdaCostCycleRiskCollector"),
    "lightsail-cost-governance-review": ("unio_collector.scanners.lightsail.collector:LightsailCostGovernanceReviewCollector"),
    "load-balancer-idle-review": ("unio_collector.scanners.collection.load_balancer:LoadBalancerIdleReviewCollector"),
    "nat-gateway-cost-review": ("unio_collector.scanners.network.nat_gateway.collector:NatGatewayCostReviewCollector"),
    "nat-gateway-inventory": ("unio_collector.scanners.network.nat_gateway.inventory.collector:NatGatewayInventoryCollector"),
    "network-privatelink-cost-review": ("unio_collector.scanners.network.privatelink.collector:NetworkPrivateLinkCostReviewCollector"),
    "network-public-ipv4-review": ("unio_collector.scanners.network.public_ipv4.collector:NetworkPublicIpv4ReviewCollector"),
    "network-transit-gateway-cost-review": ("unio_collector.scanners.network.transit_gateway.collector:NetworkTransitGatewayCostReviewCollector"),
    "network-vpc-endpoint-opportunity-review": ("unio_collector.scanners.network.vpc_endpoint.collector:NetworkVpcEndpointOpportunityReviewCollector"),
    "opensearch-cost-review": ("unio_collector.scanners.platform.opensearch.collector:OpenSearchCostReviewCollector"),
    "provisioned-iops-review": ("unio_collector.scanners.ec2.ebs.collection.provisioned:ProvisionedIopsCollector"),
    "public-service-exposure-review": ("unio_collector.scanners.security_governance.public_exposure.collector:PublicServiceExposureReviewCollector"),
    "rds-snapshot-retention-review": ("unio_collector.scanners.rds.collection.snapshots:RdsSnapshotRetentionReviewCollector"),
    "rds-utilization-review": ("unio_collector.scanners.rds.collection.utilization:RdsUtilizationReviewCollector"),
    "redshift-cost-review": ("unio_collector.scanners.platform.redshift.collector:RedshiftCostReviewCollector"),
    "root-account-recovery-advisory": ("unio_collector.scanners.account_risk.root.recovery.collector:RootAccountRecoveryAdvisoryCollector"),
    "route53-cost-governance-review": ("unio_collector.scanners.route53.collector:Route53CostGovernanceReviewCollector"),
    "s3-incomplete-multipart-review": ("unio_collector.scanners.s3.incomplete_multipart.collector:S3IncompleteMultipartReviewCollector"),
    "s3-lifecycle-cost-review": ("unio_collector.scanners.s3.lifecycle.collector:S3LifecycleCostReviewCollector"),
    "s3-public-access-security-review": ("unio_collector.scanners.s3.public_access.collector:S3PublicAccessSecurityReviewCollector"),
    "s3-versioning-and-replication-review": ("unio_collector.scanners.s3.versioning_replication.collector:S3VersioningAndReplicationReviewCollector"),
    "sagemaker-cost-review": ("unio_collector.scanners.analytics_ai.sagemaker.collector:SageMakerCostReviewCollector"),
    "secrets-manager-cost-governance-review": (
        "unio_collector.scanners.security_governance.secrets_manager.collector:SecretsManagerCostGovernanceReviewCollector"
    ),
    "securityhub-control-summary-review": (
        "unio_collector.scanners.security_governance.security_hub.summary.collector:SecurityHubControlSummaryReviewCollector"
    ),
    "securityhub-inspector-macie-cost-review": (
        "unio_collector.scanners.security_governance.securityhub_inspector_macie.collector:SecurityHubInspectorMacieCostReviewCollector"
    ),
    "service-quota-proximity-review": ("unio_collector.scanners.service_quota.collector:ServiceQuotaProximityReviewCollector"),
    "snapshot-age-review": ("unio_collector.scanners.collection.snapshots:SnapshotAgeReviewCollector"),
    "sns-cost-governance-review": ("unio_collector.scanners.sns.collector:SnsCostGovernanceReviewCollector"),
    "sqs-lambda-polling-cost-review": ("unio_collector.scanners.collection.serverless_polling:SqsLambdaPollingCostReviewCollector"),
    "step-functions-cost-governance-review": ("unio_collector.scanners.step_functions.collector:StepFunctionsCostGovernanceReviewCollector"),
    "tagging-missing-cost-tags": ("unio_collector.scanners.tagging.collector:MissingCostTagsCollector"),
    "vpc-flow-log-attribution": ("unio_collector.scanners.network.vpc_flow.attribution.collector:VpcFlowLogAttributionCollector"),
    "waf-cost-governance-review": ("unio_collector.scanners.security_governance.waf.collector:WafCostGovernanceReviewCollector"),
    "xray-tracing-cost-governance-review": ("unio_collector.scanners.xray.collector:XRayTracingCostGovernanceReviewCollector"),
}
