from __future__ import annotations  # noqa: D100

from unio_collector.scanners.registry.source import ScannerDefinitionSource
from unio_collector.scanners.scanner.definition import ScannerDefinition

COST_SCANNERS: dict[str, ScannerDefinition] = {
    "cost-explorer-service-delta": ScannerDefinition(
        scanner_id="cost-explorer-service-delta",
        display_name="Cost Explorer service delta",
        description="Compares service-level unblended cost across two matching time windows.",
        aws_services=("AWS Cost Explorer",),
        resource_types=("AWS service spend",),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=("ce:GetCostAndUsage",),
        required_permission_level="read_only",
        aws_api_calls=("ce:GetCostAndUsage",),
        risk_level="low",
        output_finding_types=("spend_increase",),
        maturity="basic",
        limitations=(
            "Uses service-level Cost Explorer data, not CUR line-item detail.",
            "Does not prove that a spend increase is avoidable.",
        ),
        execution_phase="baseline",
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=(
            "Carries Cost Explorer period data and configured delta thresholds in serialized evidence for offline spend movement analysis."
        ),
    ),
    "billing-alerts-and-budgets-review": ScannerDefinition(
        scanner_id="billing-alerts-and-budgets-review",
        display_name="Billing monitoring and budgets review",
        description="Checks for AWS Budgets, anomaly monitors, subscriptions, and billing alarms.",
        aws_services=("AWS Budgets", "AWS Cost Explorer", "Amazon CloudWatch"),
        resource_types=("Billing monitor", "Budget"),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=(
            "budgets:DescribeBudgets",
            "budgets:DescribeNotificationsForBudget",
            "budgets:DescribeSubscribersForNotification",
            "ce:GetAnomalyMonitors",
            "ce:GetAnomalySubscriptions",
            "cloudwatch:DescribeAlarms",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "budgets:DescribeBudgets",
            "budgets:DescribeNotificationsForBudget",
            "budgets:DescribeSubscribersForNotification",
            "ce:GetAnomalyMonitors",
            "ce:GetAnomalySubscriptions",
            "cloudwatch:DescribeAlarms",
        ),
        risk_level="low",
        output_finding_types=("billing_alerts_and_budgets_review",),
        maturity="experimental",
        limitations=(
            "Does not create or modify budgets, alarms, monitors, or subscriptions.",
            (
                "monitor_detail_mode can be set to budgets-only for faster development scans, "
                "but full mode is required to validate anomaly and CloudWatch billing-alarm coverage."
            ),
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=(
            "Analyzes serialized billing guardrail records without AWS clients; collection detail-mode limitations are captured in scanner evidence."
        ),
    ),
    "cost-spike-analysis": ScannerDefinition(
        scanner_id="cost-spike-analysis",
        display_name="Cost spike analysis",
        description="Uses daily Cost Explorer data to detect spend spikes in the selected window.",
        aws_services=("AWS Cost Explorer",),
        resource_types=("Daily spend",),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=("ce:GetCostAndUsage",),
        required_permission_level="read_only",
        aws_api_calls=("ce:GetCostAndUsage",),
        risk_level="low",
        output_finding_types=("cost_spike_analysis",),
        maturity="experimental",
        limitations=("Short scan windows may not provide a reliable baseline.",),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Carries daily Cost Explorer rows and scan-period metadata in serialized evidence for deterministic offline spike analysis."),
    ),
    "commitment-and-pricing-review": ScannerDefinition(
        scanner_id="commitment-and-pricing-review",
        display_name="Commitment and pricing review",
        description="Checks available AWS-native Savings Plans and Reserved Instance utilization signals.",
        aws_services=("Amazon EC2", "AWS Cost Explorer", "AWS Savings Plans"),
        resource_types=("Savings Plan", "Reserved Instance"),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "ec2:DescribeReservedInstances",
            "savingsplans:DescribeSavingsPlans",
            "ce:GetSavingsPlansUtilization",
            "ce:GetSavingsPlansCoverage",
            "ce:GetReservationUtilization",
            "ce:GetReservationCoverage",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "ec2:DescribeReservedInstances",
            "savingsplans:DescribeSavingsPlans",
            "ce:GetSavingsPlansUtilization",
            "ce:GetSavingsPlansCoverage",
            "ce:GetReservationUtilization",
            "ce:GetReservationCoverage",
        ),
        risk_level="medium",
        output_finding_types=("commitment_and_pricing_review",),
        maturity="experimental",
        limitations=(
            "Does not purchase, exchange, sell, return, retire, or modify commitments.",
            "Does not aggregate organization-wide commitment evidence.",
            "RDS, Redshift, ElastiCache, and OpenSearch reservation inventory are not collected.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Carries account id and AWS-native utilization signals in serialized evidence for offline commitment analysis."),
    ),
    "free-tier-usage-review": ScannerDefinition(
        scanner_id="free-tier-usage-review",
        display_name="Free Tier usage review",
        description=("Checks AWS Free Tier account plan state and visible usage allowance consumption where the AWS Free Tier API is available."),
        aws_services=("AWS Free Tier",),
        resource_types=("Free Tier account plan", "Free Tier usage allowance"),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=(
            "freetier:GetAccountPlanState",
            "freetier:GetFreeTierUsage",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "freetier:GetAccountPlanState",
            "freetier:GetFreeTierUsage",
        ),
        risk_level="low",
        output_finding_types=("free_tier_usage_review",),
        maturity="experimental",
        limitations=(
            "Reports allowance visibility only and does not infer savings.",
            "Does not upgrade account plans or modify billing/account settings.",
            "Free Tier API records do not provide resource-level attribution.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzes serialized Free Tier collection results without AWS clients; permission and API limitations remain explicit."),
    ),
    "account-cost-risk-signal-review": ScannerDefinition(
        scanner_id="account-cost-risk-signal-review",
        display_name="Account cost-risk signal review",
        description=("Performs lightweight FinOps checks for unexpected expensive service signals, CloudTrail visibility, and IAM account-summary context."),
        aws_services=("AWS Cost Explorer", "AWS CloudTrail", "AWS IAM"),
        resource_types=("Cost signal", "Governance signal"),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=(
            "ce:GetCostAndUsage",
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetTrailStatus",
            "iam:GetAccountSummary",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "ce:GetCostAndUsage",
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetTrailStatus",
            "iam:GetAccountSummary",
        ),
        risk_level="medium",
        output_finding_types=("account_cost_risk_signal_review",),
        maturity="experimental",
        limitations=(
            "Not a security audit and does not prove compromise.",
            "CloudTrail and IAM checks are lightweight visibility signals only.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzes serialized daily cost rows and account-risk signals without AWS clients."),
    ),
    "root-account-recovery-advisory": ScannerDefinition(
        scanner_id="root-account-recovery-advisory",
        display_name="Root account recovery advisory",
        description="Adds a non-invasive reminder to verify root email, MFA, and recovery ownership.",
        aws_services=("AWS Account",),
        resource_types=("Governance advisory",),
        default_enabled=True,
        supports_regions=False,
        required_iam_actions=("sts:GetCallerIdentity",),
        required_permission_level="read_only",
        aws_api_calls=("sts:GetCallerIdentity",),
        risk_level="low",
        output_finding_types=("root_account_recovery_advisory",),
        maturity="basic",
        limitations=("Does not verify root email access or request credentials.",),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=(
            "Collects only account-id context and builds deterministic advisory findings from serialized scanner evidence without AWS clients."
        ),
    ),
}

COST_SCANNER_DEFINITION_SOURCE = ScannerDefinitionSource(
    "cost",
    COST_SCANNERS,
)
