from __future__ import annotations  # noqa: D100

from unio_collector.scanners.registry.source import ScannerDefinitionSource
from unio_collector.scanners.scanner.definition import ScannerDefinition

UTILIZATION_SCANNERS: dict[str, ScannerDefinition] = {
    "rds-utilization-review": ScannerDefinition(
        scanner_id="rds-utilization-review",
        display_name="RDS utilization review",
        description="Reviews RDS instance inventory and available CloudWatch utilization metrics.",
        aws_services=("Amazon RDS", "Amazon CloudWatch"),
        resource_types=("RDS DB instance",),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "rds:DescribeDBInstances",
            "rds:ListTagsForResource",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetMetricStatistics",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "rds:DescribeDBInstances",
            "rds:ListTagsForResource",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetMetricStatistics",
        ),
        risk_level="medium",
        output_finding_types=("rds_utilization_review",),
        maturity="experimental",
        limitations=(
            "Uses CloudWatch metrics available to the provided identity.",
            "Does not inspect query plans, database memory, application behaviour, or maintenance windows.",
            "Does not recommend automatic resizing.",
        ),
        cloudwatch_namespaces_used=("AWS/RDS",),
        metrics_used=(
            "CPUUtilization",
            "DatabaseConnections",
            "ReadIOPS",
            "WriteIOPS",
            "FreeStorageSpace",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized regional inventory evidence without AWS clients or runtime context."),
    ),
    "load-balancer-idle-review": ScannerDefinition(
        scanner_id="load-balancer-idle-review",
        display_name="Load balancer idle review",
        description=(
            "Reviews ALB/NLB inventory, target health, and available traffic "
            "metrics. target_health_detail_mode can be set to summary for "
            "faster development scans, but target-health idle classification "
            "requires full mode."
        ),
        aws_services=("Elastic Load Balancing", "Amazon CloudWatch"),
        resource_types=("Application Load Balancer", "Network Load Balancer"),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "elasticloadbalancing:DescribeLoadBalancers",
            "elasticloadbalancing:DescribeTargetGroups",
            "elasticloadbalancing:DescribeTargetHealth",
            "elasticloadbalancing:DescribeTags",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetMetricStatistics",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "elbv2:DescribeLoadBalancers",
            "elbv2:DescribeTargetGroups",
            "elbv2:DescribeTargetHealth",
            "elbv2:DescribeTags",
            "cloudwatch:GetMetricData",
            "cloudwatch:GetMetricStatistics",
        ),
        risk_level="medium",
        output_finding_types=("load_balancer_idle_review",),
        maturity="experimental",
        limitations=(
            "Uses recent CloudWatch traffic metrics only.",
            "Does not inspect DNS, listener rule intent, certificates, or deployment workflows.",
            "Does not recommend deletion without validation.",
            "target_health_detail_mode=summary skips DescribeTargetHealth and prevents target-health-only idle classification.",
        ),
        cloudwatch_namespaces_used=("AWS/ApplicationELB", "AWS/NetworkELB"),
        metrics_used=(
            "RequestCount",
            "ProcessedBytes",
            "HealthyHostCount",
            "UnHealthyHostCount",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized load balancer inventory evidence without AWS clients or runtime context."),
    ),
    "snapshot-age-review": ScannerDefinition(
        scanner_id="snapshot-age-review",
        display_name="Snapshot age review",
        description="Finds account-owned EBS snapshots older than a configurable age threshold.",
        aws_services=("Amazon EC2", "Amazon Elastic Block Store"),
        resource_types=("EBS snapshot",),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=("ec2:DescribeRegions", "ec2:DescribeSnapshots"),
        required_permission_level="read_only",
        aws_api_calls=("ec2:DescribeRegions", "ec2:DescribeSnapshots"),
        risk_level="medium",
        output_finding_types=("snapshot_age_review",),
        maturity="experimental",
        limitations=(
            "Age alone does not prove a snapshot is waste.",
            "Does not delete snapshots or verify restore dependencies.",
            "Storage estimates require AWS Price List data and may overstate incremental snapshot cost.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized snapshot inventory evidence without AWS clients or runtime context."),
    ),
    "backup-retention-review": ScannerDefinition(
        scanner_id="backup-retention-review",
        display_name="Backup retention review",
        description=(
            "Reviews AWS Backup recovery point age, backup plan retention, "
            "selection scope, vault ownership, and calculated retention metadata "
            "where permissions allow."
        ),
        aws_services=("AWS Backup",),
        resource_types=("Backup recovery point", "Backup plan", "Backup vault"),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "backup:ListBackupVaults",
            "backup:ListRecoveryPointsByBackupVault",
            "backup:ListBackupPlans",
            "backup:GetBackupPlan",
            "backup:ListBackupSelections",
            "backup:GetBackupSelection",
            "backup:ListTags",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "backup:ListBackupVaults",
            "backup:ListRecoveryPointsByBackupVault",
            "backup:ListBackupPlans",
            "backup:GetBackupPlan",
            "backup:ListBackupSelections",
            "backup:GetBackupSelection",
            "backup:ListTags",
        ),
        risk_level="medium",
        output_finding_types=("backup_retention_review",),
        maturity="experimental",
        limitations=(
            "Does not delete recovery points or validate restore chains.",
            "Does not prove retention is excessive without owner and restore-policy validation.",
            "selection_detail_mode can be set to summary for faster development scans, but full mode is required to validate broad backup selection scope.",
            "collect_tags can be disabled for faster development scans, but tag collection is required for backup ownership-tag review.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized Backup inventory evidence and replay thresholds from evidence metadata."),
    ),
    "rds-snapshot-retention-review": ScannerDefinition(
        scanner_id="rds-snapshot-retention-review",
        display_name="RDS snapshot retention review",
        description=("Finds old account-owned manual RDS DB and DB cluster snapshots for backup retention and ownership review."),
        aws_services=("Amazon RDS",),
        resource_types=("RDS DB snapshot", "RDS DB cluster snapshot"),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "rds:DescribeDBSnapshots",
            "rds:DescribeDBClusterSnapshots",
            "rds:ListTagsForResource",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "rds:DescribeDBSnapshots",
            "rds:DescribeDBClusterSnapshots",
            "rds:ListTagsForResource",
        ),
        risk_level="medium",
        output_finding_types=("rds_snapshot_retention_review",),
        maturity="experimental",
        limitations=(
            "Age alone does not prove a manual database snapshot is waste.",
            "Does not delete snapshots or validate restore/compliance requirements.",
            "Does not estimate exact RDS backup storage cost without billing export evidence.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized RDS snapshot inventory evidence without AWS clients or runtime context."),
    ),
    "extended-support-and-eol-review": ScannerDefinition(
        scanner_id="extended-support-and-eol-review",
        display_name="Extended support and EOL review",
        description=("Reviews exposed runtime and engine versions for extended support or end-of-life planning signals."),
        aws_services=(
            "Amazon RDS",
            "AWS Lambda",
            "Amazon EC2",
            "Amazon ElastiCache",
            "Amazon OpenSearch Service",
            "Amazon EKS",
        ),
        resource_types=(
            "RDS instance",
            "Lambda function",
            "EC2 instance AMI",
            "ElastiCache cluster",
            "OpenSearch domain",
            "EKS cluster",
        ),
        default_enabled=True,
        supports_regions=True,
        required_iam_actions=(
            "rds:DescribeDBInstances",
            "rds:ListTagsForResource",
            "lambda:ListFunctions",
            "ec2:DescribeInstances",
            "ec2:DescribeImages",
            "elasticache:DescribeCacheClusters",
            "opensearch:ListDomainNames",
            "opensearch:DescribeDomains",
            "eks:ListClusters",
            "eks:DescribeCluster",
        ),
        required_permission_level="read_only",
        aws_api_calls=(
            "rds:DescribeDBInstances",
            "rds:ListTagsForResource",
            "lambda:ListFunctions",
            "ec2:DescribeInstances",
            "ec2:DescribeImages",
            "elasticache:DescribeCacheClusters",
            "opensearch:ListDomainNames",
            "opensearch:DescribeDomains",
            "eks:ListClusters",
            "eks:DescribeCluster",
        ),
        risk_level="medium",
        output_finding_types=("extended_support_and_eol_review",),
        maturity="experimental",
        limitations=(
            "Uses versioned local lifecycle metadata that must be verified against official AWS documentation.",
            "EC2 AMI review is age and provenance evidence, not proof of operating-system patch status.",
            "Does not upgrade or modify resources.",
        ),
        analysis_boundary="strict_evidence_only_ready",
        analysis_boundary_reason=("Analyzer consumes serialized lifecycle inventory evidence; summary side-channel writes are optional during strict replay."),
    ),
}

UTILIZATION_SCANNER_DEFINITION_SOURCE = ScannerDefinitionSource(
    "utilization",
    UTILIZATION_SCANNERS,
)
