"""Exact privacy fields for collector-generated product, billing and limitation provenance."""

PRODUCT_FIELDS = {
    "": "safe_metadata",
    "definition_version": "free_text",
    "out_of_product_overrides": "sequence",
    "period_policy": "safe_metadata",
    "period_policy.default_duration_days": "safe_metadata",
    "period_policy.maximum_duration_days": "safe_metadata",
    "period_policy.policy_id": "free_text",
    "primary_report_order": "sequence",
    "primary_report_order[]": "free_text",
    "product_id": "free_text",
    "registry_version": "free_text",
    "report_label": "free_text",
    "report_set_id": "free_text",
    "selection_source": "free_text",
    "out_of_product_overrides[]": "free_text",
}

BILLING_FIELDS = {
    "": "safe_metadata",
    "status": "free_text",
    "selected_regions": "sequence",
    "selected_regions[]": "region",
    "explicit_region_scope": "safe_metadata",
    "materiality_threshold": "cost",
    "billing_active_regions": "sequence",
    "billing_active_regions[]": "region",
    "billing_active_regions_outside_scan": "sequence",
    "billing_active_regions_outside_scan[]": "region",
    "material_billing_active_regions": "sequence",
    "material_billing_active_regions[]": "region",
    "residual_billing_active_regions": "sequence",
    "material_billing_active_regions_outside_scan": "sequence",
    "material_billing_active_regions_outside_scan[]": "region",
    "residual_billing_active_regions_outside_scan": "sequence",
    "outside_scan_count": "safe_metadata",
    "material_outside_scan_count": "safe_metadata",
    "residual_outside_scan_count": "safe_metadata",
    "billing_region_count": "safe_metadata",
    "billing_global_or_unallocated_cost": "cost",
    "currency": "cost",
    "current_period": "safe_metadata",
    "current_period.start_date": "timestamp",
    "current_period.end_date": "timestamp",
    "region_costs": "sequence",
    "region_costs[]": "safe_metadata",
    "region_costs[].region": "region",
    "region_costs[].current_cost": "cost",
    "region_costs[].currency": "cost",
    "region_costs[].selected_for_scan": "safe_metadata",
    "region_costs[].material": "safe_metadata",
    "region_costs[].outside_selected_scan_scope": "safe_metadata",
    "material_warning_required": "safe_metadata",
    "residual_notice_required": "safe_metadata",
    "notice_required": "safe_metadata",
    "notice_severity": "free_text",
    "limitations": "sequence",
    "unrecognized_billing_region_values": "sequence",
    "residual_billing_active_regions[]": "region",
    "residual_billing_active_regions_outside_scan[]": "region",
    "limitations[]": "free_text",
    "unrecognized_billing_region_values[]": "region",
}

LIMITATION_FIELDS = {
    "": "safe_metadata",
    "account_id": "aws_account_id",
    "affected_fields": "sequence",
    "affected_fields[]": "free_text",
    "api_action": "free_text",
    "category": "free_text",
    "client_explanation": "free_text",
    "collection_continued": "safe_metadata",
    "confidence_effect": "free_text",
    "evidence_categories": "sequence",
    "evidence_categories[]": "free_text",
    "evidence_interpretation": "free_text",
    "iam_action_requirement": "free_text",
    "outcome": "free_text",
    "record_id": "resource_id",
    "region": "region",
    "related_findings_may_be_incomplete": "safe_metadata",
    "remediation_permission": "free_text",
    "requested_account_id": "aws_account_id",
    "requested_region": "region",
    "requirement_type": "free_text",
    "resource_id": "resource_id",
    "resource_type": "free_text",
    "safe_scope": "free_text",
    "scanner_continued": "safe_metadata",
    "scanner_id": "free_text",
    "service": "free_text",
}

DERIVATION_FIELDS = {
    "": "safe_metadata",
    **dict.fromkeys(("enabled", "global_checks_enabled"), "safe_metadata"),
    **dict.fromkeys(("status", "reason", "source", "fallback_behavior"), "free_text"),
    "materiality_threshold": "cost",
    **dict.fromkeys(
        (
            "requested_regions",
            "derived_material_regions",
            "billing_active_regions",
            "normalized_candidate_regions",
            "residual_regions",
            "unrecognized_billing_region_values",
            "final_regions",
        ),
        "sequence",
    ),
    **{
        f"{key}[]": "region"
        for key in (
            "requested_regions",
            "derived_material_regions",
            "billing_active_regions",
            "normalized_candidate_regions",
            "residual_regions",
            "unrecognized_billing_region_values",
            "final_regions",
        )
    },
}


SUMMARY_COUNTS = {
    "limitation_counts": (
        "chargeable_api_disabled",
        "permission_denied",
        "endpoint_unavailable",
        "expected_absence",
        "inferred",
        "scanner_failed",
        "unknown",
        "partial",
        "service_not_enabled",
        "stale",
        "unsupported_operation",
        "unsupported_region",
    ),
    "stable_limitation_counts": (
        "required_permission_denied",
        "optional_enrichment_permission_denied",
        "evidence_unavailable",
        "evidence_unsupported",
        "scanner_execution_degraded",
    ),
    "secondary_classification_counts": (
        "expected_absence",
        "service_unavailable",
        "permission_denied",
        "throttling",
        "unsupported_operation",
        "unsupported_region",
        "failure",
        "access_denied_policy_source_unknown",
        "chargeable_api_disabled",
        "interrupted",
        "partial_collection",
        "unknown",
        "legacy_limitation",
        "completed",
        "completed_with_warnings",
        "disabled",
        "failed",
        "skipped",
        "unavailable",
    ),
}
SUMMARY_LIMITATIONS = {
    "": "sequence",
    "[]": "safe_metadata",
    **dict.fromkeys(("[].type", "[].service", "[].reason", "[].permission"), "free_text"),
}

BILLING_FIELDS.update({"region_scope_derivation" + ("." + key if key else ""): category for key, category in DERIVATION_FIELDS.items()})


def valid_summary_count(value: object) -> bool:
    """Require non-negative integer counts, excluding booleans, labels and financial values."""
    return type(value) is int and value >= 0
