from __future__ import annotations  # noqa: D100

FALLBACK_SENSITIVE_KEY_CATEGORIES = {
    "account_id": "aws_account_id",
    "account": "aws_account_id",
    "account_label": "resource_name",
    "owner_account_id": "aws_account_id",
    "recipient_account_id": "aws_account_id",
    "requested_account_id": "aws_account_id",
    "arn": "arn",
    "resource_arn": "arn",
    "function_arn": "arn",
    "queue_arn": "arn",
    "source_arn": "arn",
    "target_arn": "arn",
    "principal_arn": "arn",
    "policy_arn": "arn",
    "analyzer_arn": "arn",
    "repository_arn": "arn",
    "instance_arn": "arn",
    "permission_set_arn": "arn",
    "backup_plan_arn": "arn",
    "backup_vault_arn": "arn",
    "recovery_point_arn": "arn",
    "resource_id": "resource_id",
    "raw_reference_id": "resource_id",
    "finding_id": "resource_id",
    "user_id": "resource_id",
    "access_key_id": "resource_id",
    "key_id": "resource_id",
    "kms_key_id": "resource_id",
    "kms_key": "resource_id",
    "secret_id": "resource_id",
    "secret_arn": "arn",
    "snapshot_id": "resource_id",
    "volume_id": "resource_id",
    "instance_id": "resource_id",
    "vpc_id": "resource_id",
    "subnet_id": "resource_id",
    "group_id": "resource_id",
    "security_group_id": "resource_id",
    "allocation_id": "resource_id",
    "function_name": "resource_name",
    "resource_name": "resource_name",
    "name": "resource_name",
    "user_name": "resource_name",
    "principal_name": "resource_name",
    "role_name": "iam_role",
    "policy_name": "resource_name",
    "bucket_name": "bucket_name",
    "s3_bucket_name": "bucket_name",
    "backup_vault_name": "resource_name",
    "backup_plan_name": "resource_name",
    "database_identifier": "resource_name",
    "database_name": "resource_name",
    "db_identifier": "resource_name",
    "db_instance_identifier": "resource_name",
    "db_cluster_identifier": "resource_name",
    "endpoint": "dns_name",
    "endpoint_address": "dns_name",
    "db_endpoint": "dns_name",
    "database_endpoint": "dns_name",
    "hostname": "dns_name",
    "host": "dns_name",
    "domain": "dns_name",
    "domain_name": "dns_name",
    "origin_domain": "dns_name",
    "origin_domain_name": "dns_name",
    "url": "url",
    "email": "email",
    "account_email": "email",
    "kms_alias": "resource_name",
    "alias_name": "resource_name",
    "secret_name": "resource_name",
    "principal": "resource_name",
    "policy_principal": "resource_name",
    "policy_resource": "resource_id",
    "source_resource_id": "resource_id",
    "target_resource_id": "resource_id",
    "source_resource_name": "resource_name",
    "target_resource_name": "resource_name",
    "cidr": "cidr",
    "cidrip": "cidr",
    "cidripv6": "cidr",
    "public_ip": "ipv4",
    "ip_address": "ipv4",
    "ipv4": "ipv4",
    "ipv6": "ipv6",
}

FALLBACK_TEXT_KEYS = {
    "errors",
    "warnings",
    "limitations",
    "reason",
    "skip_reason",
    "disabled_reason",
    "client_explanation",
    "do_not_do",
    "technical_detail",
    "downstream_effect",
    "description",
    "detail",
    "facts",
    "hypotheses",
    "safe_checks",
    "suggested_actions",
    "title",
    "business_impact",
    "error",
    "exception",
    "exception_message",
    "expected_outcome",
    "implementation_risk",
    "likely_root_cause",
    "message",
    "owner_action_required",
    "recurrence_risk",
    "technical_impact",
    "traceback",
}

FALLBACK_SAFE_STRING_KEYS = {
    "algorithm",
    "active_analysis_source",
    "affected_scanner_ids",
    "affected_services",
    "analysis_state",
    "analyzer_entrypoint",
    "assessment_method",
    "bundle_purpose",
    "bundle_schema_version",
    "category",
    "compatibility_role",
    "completed_at",
    "collection_mode",
    "collection_status",
    "collector_id",
    "collector_version",
    "confidence",
    "confidence_effect",
    "conditional_iam_actions",
    "contains_completed_report_bundle",
    "contains_normalized_evidence_records",
    "contains_scanner_execution_results",
    "contract_type",
    "collection_time",
    "created_at",
    "currency",
    "current_cost",
    "deferred_reason",
    "deferred_scanner_ids",
    "digest_algorithm",
    "disabled_scanner_ids",
    "display_name",
    "duplicate_payload_ids",
    "encoding",
    "end_date",
    "error_code",
    "error_classification",
    "evidence_category",
    "evidence_categories",
    "evidence_generated_at",
    "evidence_id",
    "evidence_interpretation",
    "evidence_module",
    "evidence_type",
    "excluded_services",
    "failed_scanner_ids",
    "finding_type",
    "format",
    "full_report_rebuild_from_scanner_evidence_supported",
    "generated_at",
    "implementation_class",
    "implementation_module",
    "implementation_type",
    "key_id",
    "malformed_payload_indexes",
    "metadata_version",
    "missing_payload_ids",
    "missing_scanner_evidence_payload_ids",
    "mode",
    "not_attempted_actions",
    "operation_limitations",
    "occurrence_count",
    "no_cost_data",
    "outcome",
    "package_version",
    "partition",
    "path_format",
    "payload_format",
    "provider",
    "provider_mismatch_payload_ids",
    "provider_id",
    "previous_cost",
    "redact_before_export",
    "record_id",
    "region",
    "regions",
    "regions_scanned",
    "required_for_full_report_rebuild",
    "required_permission_level",
    "required_iam_actions",
    "api_action",
    "resource_type",
    "affected_fields",
    "requirement_type",
    "requested_region",
    "remediation_permission",
    "safe_scope",
    "scope_status",
    "requires_aws_for_analysis",
    "requires_credentials_for_analysis",
    "result_bundle_only_count",
    "result_bundle_only_scanner_count",
    "risk_level",
    "scanner_count",
    "scanner_id",
    "scanner_evidence_count",
    "scanner_evidence_payload_count",
    "scanner_evidence_payload_file",
    "scanner_evidence_payload_ids",
    "scanner_evidence_payloads_serialized",
    "scanner_status",
    "selected_scanner_ids",
    "selected_regions",
    "schema_version",
    "serialization_format",
    "serialization_status",
    "service",
    "service_name",
    "services_attempted",
    "services_collected",
    "severity",
    "signature_algorithm",
    "signed_payload",
    "skipped_scanner_ids",
    "source",
    "source_scanner_id",
    "scanned_regions",
    "start_date",
    "started_at",
    "timestamp",
    "status",
    "strict_evidence_only_analysis_supported",
    "strict_evidence_only_ready_count",
    "strict_evidence_only_ready_scanner_count",
    "strict_evidence_only_report_rebuild_deferred_reason",
    "strict_evidence_only_report_rebuild_supported",
    "strict_evidence_only_support_scope",
    "strict_scanner_analyzer_replay_scope",
    "strict_scanner_analyzer_replay_supported",
    "successful_scanner_ids",
    "total_cost",
    "type",
    "aws_api_calls",
    "unavailable_scanner_ids",
    "unexpected_payload_ids",
    "unknown_payload_ids",
    "unserialized_payload_ids",
    "validation_errors",
    "api_call_count",
    "authoritative_for_analysis",
    "checksums",
    "deterministic_report_parity",
    "duration_ms",
    "enabled",
    "estimated_monthly_saving_converted_currency",
    "estimated_monthly_saving_source_currency",
    "evidence_count",
    "evidence_files",
    "finding_count",
    "findings_count",
    "follow_up_interval",
    "limitation_count",
    "minimisation",
    "optional_files",
    "permission_degradation_record_count",
    "priority",
    "record_count",
    "required_files",
    "result_bundle_only",
    "scanner_analysis_boundary_summary",
    "service_evidence_files",
    "signature",
    "strict_evidence_only_ready",
}

REMOVED_KEY_CATEGORIES = {
    "fixture": "local_path_or_profile",
    "profile_name": "local_path_or_profile",
    "replay_aws_cassette": "local_path_or_profile",
    "source_path": "local_path_or_profile",
}

PROHIBITED_KEY_CATEGORIES = {
    "client_root_key": "private_material",
    "decrypted_vault": "private_material",
    "encrypted_root_key": "private_material",
    "identity_vault": "private_material",
    "passphrase": "private_material",
    "private_key": "private_material",
    "recovery_key": "private_material",
    "recovery_key_bytes": "private_material",
    "root_key": "private_material",
    "vault_ciphertext": "private_material",
    "vault_plaintext": "private_material",
    "wrapped_root_key": "private_material",
}

STRICT_REMOVE_KEYS = {
    "cost",
    "current_cost",
    "estimated_monthly_saving",
    "estimated_monthly_saving_converted",
    "total_cost",
    "previous_cost",
    "saving",
    "savings",
    "spend",
    "price",
    "amount",
    "charge",
    "billing",
    "rate",
}

STRICT_GENERALISE_KEYS = {
    "timestamp": "timestamp",
    "time": "timestamp",
    "date": "timestamp",
    "created_at": "timestamp",
    "updated_at": "timestamp",
    "started_at": "timestamp",
    "completed_at": "timestamp",
    "generated_at": "timestamp",
    "region": "region",
    "regions": "region",
    "scanned_regions": "region",
    "selected_regions": "region",
}

STRICT_TOPOLOGY_KEYS = {
    "topology",
    "relationship",
    "relationships",
    "route_table",
    "routes",
    "attachment",
    "attachments",
    "edges",
    "network_path",
}
