from unio_collector.aws.core.error.classification import AwsErrorClassification  # noqa: D100
from unio_collector.aws.core.error.defaults import (
    DEFAULT_ERROR_CLASSIFICATION_POLICY,
    SERVICE_UNAVAILABLE_ERROR_RULES,
    classify_aws_error,
    is_expected_absence_error,
    is_permission_error,
    is_retryable_error,
    is_service_unavailable_error,
    is_throttling_error,
    is_unsupported_operation_error,
    is_unsupported_region_error,
)
from unio_collector.aws.core.error.helpers import (
    EXPECTED_ABSENCE_ERROR_CODES,
    PERMISSION_ERROR_MARKERS,
    SERVICE_UNAVAILABLE_ERROR_MESSAGE_MARKERS,
    THROTTLE_ERROR_CODES,
    UNSUPPORTED_REGION_ERROR_CODES,
    AwsErrorCategory,
    ServiceAvailabilityStatus,
    get_aws_error_code,
    get_aws_error_message,
    is_expected_absence_error_code,
    is_permission_error_code,
)
from unio_collector.aws.core.error.policy import AwsErrorClassificationPolicy
from unio_collector.aws.service.unavailable_rule import ServiceUnavailableErrorRule

__all__ = [
    "DEFAULT_ERROR_CLASSIFICATION_POLICY",
    "EXPECTED_ABSENCE_ERROR_CODES",
    "PERMISSION_ERROR_MARKERS",
    "SERVICE_UNAVAILABLE_ERROR_MESSAGE_MARKERS",
    "SERVICE_UNAVAILABLE_ERROR_RULES",
    "THROTTLE_ERROR_CODES",
    "UNSUPPORTED_REGION_ERROR_CODES",
    "AwsErrorCategory",
    "AwsErrorClassification",
    "AwsErrorClassificationPolicy",
    "ServiceAvailabilityStatus",
    "ServiceUnavailableErrorRule",
    "classify_aws_error",
    "get_aws_error_code",
    "get_aws_error_message",
    "is_expected_absence_error",
    "is_expected_absence_error_code",
    "is_permission_error",
    "is_permission_error_code",
    "is_retryable_error",
    "is_service_unavailable_error",
    "is_throttling_error",
    "is_unsupported_operation_error",
    "is_unsupported_region_error",
]
