"""Frozen Custex version-one scanner membership."""

CUSTEX_SCANNERS = (
    "active-security-finding-review",
    "aws-config-compliance-review",
    "aws-security-service-coverage-review",
    "backup-retention-review",
    "cloudfront-alb-origin-protection-review",
    "cloudfront-origin-cost-review",
    "cloudtrail-security-posture-review",
    "cloudwatch-log-groups-without-retention",
    "ec2-security-group-exposure-review",
    "ecr-image-scan-posture-review",
    "eks-cost-risk-review",
    "elasticache-cost-review",
    "encryption-baseline-review",
    "extended-support-and-eol-review",
    "iam-access-analyzer-evidence-review",
    "iam-account-security-review",
    "iam-identity-center-visibility-review",
    "kms-key-posture-review",
    "lightsail-cost-governance-review",
    "network-public-ipv4-review",
    "opensearch-cost-review",
    "public-service-exposure-review",
    "rds-snapshot-retention-review",
    "redshift-cost-review",
    "root-account-recovery-advisory",
    "s3-public-access-security-review",
    "s3-versioning-and-replication-review",
    "securityhub-control-summary-review",
    "securityhub-inspector-macie-cost-review",
    "waf-cost-governance-review",
)
