from __future__ import annotations  # noqa: D100

PROTECTED_REPORT_PACKAGE_V1_SCHEMA_VERSION = "2026-03-protected-report-package-json-v1"
PROTECTED_REPORT_PACKAGE_V2_SCHEMA_VERSION = "2026-08-protected-report-package-json-v2"
PROTECTED_REPORT_PACKAGE_V1_TYPE = "unio_protected_report_package_json_v1"
PROTECTED_REPORT_PACKAGE_V2_TYPE = "unio_protected_report_package_json_v2"
PROTECTED_REPORT_PACKAGE_SCHEMA_VERSION = PROTECTED_REPORT_PACKAGE_V1_SCHEMA_VERSION
PROTECTED_REPORT_PACKAGE_TYPE = PROTECTED_REPORT_PACKAGE_V1_TYPE
PROTECTED_RENDER_REPORT_VERSION = "2026-08-protected-report-v1"
PROTECTED_RENDER_TABLE_VERSION = "2026-08-protected-table-v1"
PROTECTED_RENDER_DIAGRAM_VERSION = "2026-08-protected-mermaid-v1"
PROTECTED_REPORT_PACKAGE_FILENAME = "protected-report-package.json"
PROTECTED_REPORT_PACKAGE_RELATIVE_PATH = "data/privacy/protected-report-package.json"
PROTECTED_REPORT_PACKAGE_UNSIGNED_STATUS = "unsigned"
PROTECTED_REPORT_PACKAGE_SIGNED_STATUS = "signed"
PROTECTED_REPORT_PACKAGE_SIGNATURE_ALGORITHM = "Ed25519"
PROTECTED_REPORT_PACKAGE_SIGNED_PAYLOAD = "package_without_signature"
