"""Offline daily-cost fixtures generated by the real collectors and period resolver."""

from __future__ import annotations

from datetime import date
from typing import Any
from unittest.mock import Mock

from tools.collector_scanner_fixture import add_scanner_producer_payload
from unio_collector.aws.cost_explorer.response_parser import CostExplorerResponseParser
from unio_collector.core.scan.period_resolver import ScanPeriodResolver
from unio_collector.scanners.cost_explorer.spike.collector import CostSpikeAnalysisCollector
from unio_collector.scanners.data_transfer.collector import DataTransferCostReviewCollector
from unio_collector.scanners.scanner.evidence_serializer import build_scanner_evidence_payload

SCANNERS = {"cost-spike-analysis": CostSpikeAnalysisCollector, "data-transfer-cost-review": DataTransferCostReviewCollector}
PERIODS = {"days": {"days": 14}, "months": {"months": 2}, "years": {"years": 1}, "date_range": {"date_from": "2026-09-01", "date_to": "2026-09-30"}}


def daily_producer_payload(scanner_id: str, period_kind: str = "date_range", *, empty: bool = False) -> dict[str, Any]:
    """Invoke real parser, selected collector and serializer with no SDK endpoint."""
    response = {
        "ResultsByTime": [
            {
                "TimePeriod": {"Start": "2026-09-01", "End": "2026-09-02"},
                "Groups": []
                if empty
                else [{"Keys": ["Amazon EC2", "DataTransfer-Out-Bytes"], "Metrics": {"UnblendedCost": {"Amount": "12.75", "Unit": "USD"}}}],
            }
        ]
    }
    context = Mock()
    context.costs.collect_daily_costs.side_effect = lambda *, group_keys: CostExplorerResponseParser().parse_daily_cost_response(response, group_keys)
    options: dict[str, Any] = PERIODS[period_kind] if period_kind != "none" else {}
    context.options.get_scan_period.return_value = ScanPeriodResolver().resolve(reference_date=date(2026, 10, 1), **options) if period_kind != "none" else None
    evidence = SCANNERS[scanner_id](Mock(scanner_id=scanner_id)).collect(context)
    return build_scanner_evidence_payload(scanner_id=scanner_id, evidence=evidence)


def add_daily_producer_payloads(files: dict[str, bytes], *, unknown_field: bool = False) -> None:
    """Include actual nonempty daily evidence in the distributed native smoke input."""
    for scanner_id in SCANNERS:
        row = daily_producer_payload(scanner_id)
        if unknown_field:
            row["payload"]["scan_period"]["raw_input"]["unknown_synthetic_field"] = None
        add_scanner_producer_payload(files, row)
